server:
  port: 8081
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:products
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-ui
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  main:
    banner-mode: 'off'
  output:
    ansi:
      enabled: ALWAYS
